DROP SCHEMA IF EXISTS catalogo CASCADE;
DROP TABLE IF EXISTS catalogo.subgrupo_catalogo CASCADE;
DROP TABLE IF EXISTS catalogo.catalogo CASCADE;
DROP TABLE IF EXISTS catalogo.subgrupo CASCADE;
DROP TABLE IF EXISTS catalogo.subgrupo_subgrupo CASCADE;
DROP TABLE IF EXISTS catalogo.cuentas_grupo CASCADE;
DROP TABLE IF EXISTS catalogo.tipo_bien CASCADE;
DROP TABLE IF EXISTS catalogo.tipo_jerarquia CASCADE;
DROP TABLE IF EXISTS catalogo.elemento CASCADE;